date.timezone = "Asia/Tokyo"

[mbstring]
; mbstring.internal_encoding = "UTF-8"
mbstring.language = "Japanese"
curl.cainfo = "/etc/ssl/certs/ca-certificates.crt"
openssl.cafile = "/etc/ssl/certs/ca-certificates.crt"
openssl.capath = "/etc/ssl/certs/"